version: '3.7'

services:
  bot:
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./utils/users-orm.sqlite:/app/utils/users-orm.sqlite
      - ./PingBot.session:/app/PingBot.session
    restart: unless-stopped