version: '3.7'

services:
  bot:
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./users.db:/app/users.db
      - ./PingBot.session:/app/PingBot.session
    restart: unless-stopped